services:
  - type: web
    name: hr-payroll-tool
    runtime: node
    plan: free
    buildCommand: |
      npm install
      sqlite3 hr_payroll.db < sql/hr_payroll_dump.sql
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_PATH
        value: ./hr_payroll.db
